- BOW(Bag of Words)   
- TF-IDF(Term Frequency - Inverse Document Frequency)   
- 앞으로는 Word Embedding으로 Keras word API 사용

In [1]:
import pandas as pd

# Let It Be Forgotten by Sara Teasdale
sentences = ['Let it be forgotten as a flower is forgotten,',
             'Forgotten as a fire that once was singing gold.',
             'Let it be forgotten forever and ever.',
             'Time is a kind friend, he will make us old.',
             'If anyone should ask say it was forgotten,',
             'Long and long ago. As a flower, as a fire, as a hushed foot-fall',
             'In a long forgotten snow.']

## 1. Bag of Word(BOW)

- CountVectorizer   
  - min_df: vocabulary에 포함할 최소 발생 빈도  
  - ngram_range: (1,1) unigram / (1,2) unigram+bigram  
  - max_features: top max_features 만으로 vocabulary 구성   
  - token_pattern = (?u)\b\w\w+\b: uncode 영숫자 2글자 이상만 포함   
    - \b boundary, \w 단어  
    - a dog 에서 'a' 빠짐

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
count_vectorizer

CountVectorizer()

### Text vs token Matrix 생성

In [3]:
features = count_vectorizer.fit_transform(sentences) # 학습시키는 것것
features

<7x36 sparse matrix of type '<class 'numpy.int64'>'
	with 52 stored elements in Compressed Sparse Row format>

sparse matrix: 0이 많이 채워져 있는 데이터는 굉장히 메모리 loss가 많다, 그래서 파이썬이 이를 보완하기 위해 가지고 있는 특수한 형태

In [4]:
features.shape

(7, 36)

In [7]:
vectorized_sentences = features.toarray()
print("feature/column name:", count_vectorizer.get_feature_names())
print(vectorized_sentences)

feature/column name: ['ago', 'and', 'anyone', 'as', 'ask', 'be', 'ever', 'fall', 'fire', 'flower', 'foot', 'forever', 'forgotten', 'friend', 'gold', 'he', 'hushed', 'if', 'in', 'is', 'it', 'kind', 'let', 'long', 'make', 'old', 'once', 'say', 'should', 'singing', 'snow', 'that', 'time', 'us', 'was', 'will']
[[0 0 0 1 0 1 0 0 0 1 0 0 2 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0]
 [0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1]
 [0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0]
 [1 1 0 3 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]]


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [6]:
df = pd.DataFrame(vectorized_sentences, columns=count_vectorizer.get_feature_names())
df

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ago  and  anyone  as  ask  be  ever  fall  fire  flower  ...  once  say  \
0    0    0       0   1    0   1     0     0     0       1  ...     0    0   
1    0    0       0   1    0   0     0     0     1       0  ...     1    0   
2    0    1       0   0    0   1     1     0     0       0  ...     0    0   
3    0    0       0   0    0   0     0     0     0       0  ...     0    0   
4    0    0       1   0    1   0     0     0     0       0  ...     0    1   
5    1    1       0   3    0   0     0     1     1       1  ...     0    0   
6    0    0       0   0    0   0     0     0     0       0  ...     0    0   

   should  singing  snow  that  time  us  was  will  
0       0        0     0     0     0   0    0     0  
1       0        1     0     1     0   0    1     0  
2       0        0     0     0     0   0    0     0  
3       0        0     0     0     1   1    0     1  
4       1        0     0     0     0   0    1     0  
5       0        0     0     0     0   0    0     0  
6       0        0     1     0     0   0    0     0  

[7 rows x 36 columns]

BOW는 단순하게 문장 안에서 몇 번 자주 나타난 건지를 나타내는 것

## 2. TF-IDF
Term Frequency-Inverse Document Frequency

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer

TfidfVectorizer()

In [10]:
tfidf_sentences = tfidf_vectorizer.fit_transform(sentences)
tfidf_sentences

<7x36 sparse matrix of type '<class 'numpy.float64'>'
	with 52 stored elements in Compressed Sparse Row format>

In [11]:
tfidf_vect_sentences = tfidf_sentences.toarray()
tfidf_vect_sentences

array([[0.        , 0.        , 0.        , 0.31962828, 0.        ,
        0.37393622, 0.        , 0.        , 0.        , 0.37393622,
        0.        , 0.        , 0.4861711 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.37393622,
        0.31962828, 0.        , 0.37393622, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.28558343, 0.        ,
        0.        , 0.        , 0.        , 0.33410682, 0.        ,
        0.        , 0.        , 0.21719356, 0.        , 0.40249669,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40249669, 0.        , 0.        , 0.40249669,
        0.        , 0.40249669, 0.        , 0.        , 0.33410682,
        0.        ],
      

뭔가 normalized된 형태임

In [12]:
df = pd.DataFrame(tfidf_vect_sentences, columns=tfidf_vectorizer.get_feature_names())
df

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ago       and    anyone        as       ask        be      ever  \
0  0.000000  0.000000  0.000000  0.319628  0.000000  0.373936  0.000000   
1  0.000000  0.000000  0.000000  0.285583  0.000000  0.000000  0.000000   
2  0.000000  0.376467  0.000000  0.000000  0.000000  0.376467  0.453528   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.392726  0.000000  0.392726  0.000000  0.000000   
5  0.273647  0.227151  0.000000  0.582483  0.000000  0.000000  0.000000   
6  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

       fall      fire    flower  ...      once       say    should   singing  \
0  0.000000  0.000000  0.373936  ...  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.334107  0.000000  ...  0.402497  0.000000  0.000000  0.402497   
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.000000  ...  0.000000  0.392726  0.392726  0.000000   
5  0.273647  0.227151  0.227151  ...  0.000000  0.000000  0.000000  0.000000   
6  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

       snow      that      time        us       was      will  
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1  0.000000  0.402497  0.000000  0.000000  0.334107  0.000000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3  0.000000  0.000000  0.339245  0.339245  0.000000  0.339245  
4  0.000000  0.000000  0.000000  0.000000  0.325996  0.000000  
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
6  0.579262  0.000000  0.000000  0.000000  0.000000  0.000000  

[7 rows x 36 columns]

## 3. keras word encoding 
- keras API 이용   

In [13]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences # 줄 길이 맞춰주는 거
from tensorflow.keras.utils import to_categorical # 원핫인코딩

In [14]:
tokenizer = Tokenizer(num_words=100, oov_token = '<OOV>') 
  # num_words = vocab 사전 만들 건데 몇 단어짜리일 건지
  # oov_token = 단어사전에 없는 건 어떻게 표시할 거냐. 보통은 oov, unk

In [15]:
tokenizer.fit_on_texts(sentences)
tokenizer.word_index
# 파이썬 딕셔너리 특징, 순서가 없다. 

{'<OOV>': 1,
 'a': 2,
 'forgotten': 3,
 'as': 4,
 'it': 5,
 'long': 6,
 'let': 7,
 'be': 8,
 'flower': 9,
 'is': 10,
 'fire': 11,
 'was': 12,
 'and': 13,
 'that': 14,
 'once': 15,
 'singing': 16,
 'gold': 17,
 'forever': 18,
 'ever': 19,
 'time': 20,
 'kind': 21,
 'friend': 22,
 'he': 23,
 'will': 24,
 'make': 25,
 'us': 26,
 'old': 27,
 'if': 28,
 'anyone': 29,
 'should': 30,
 'ask': 31,
 'say': 32,
 'ago': 33,
 'hushed': 34,
 'foot': 35,
 'fall': 36,
 'in': 37,
 'snow': 38}

In [16]:
tokenizer.index_word
# 순서 거꾸로

{1: '<OOV>',
 2: 'a',
 3: 'forgotten',
 4: 'as',
 5: 'it',
 6: 'long',
 7: 'let',
 8: 'be',
 9: 'flower',
 10: 'is',
 11: 'fire',
 12: 'was',
 13: 'and',
 14: 'that',
 15: 'once',
 16: 'singing',
 17: 'gold',
 18: 'forever',
 19: 'ever',
 20: 'time',
 21: 'kind',
 22: 'friend',
 23: 'he',
 24: 'will',
 25: 'make',
 26: 'us',
 27: 'old',
 28: 'if',
 29: 'anyone',
 30: 'should',
 31: 'ask',
 32: 'say',
 33: 'ago',
 34: 'hushed',
 35: 'foot',
 36: 'fall',
 37: 'in',
 38: 'snow'}

In [17]:
sequences = tokenizer.texts_to_sequences(sentences) # 문장을 숫자로 바꾸기
sequences

[[7, 5, 8, 3, 4, 2, 9, 10, 3],
 [3, 4, 2, 11, 14, 15, 12, 16, 17],
 [7, 5, 8, 3, 18, 13, 19],
 [20, 10, 2, 21, 22, 23, 24, 25, 26, 27],
 [28, 29, 30, 31, 32, 5, 12, 3],
 [6, 13, 6, 33, 4, 2, 9, 4, 2, 11, 4, 2, 34, 35, 36],
 [37, 2, 6, 3, 38]]

In [18]:
sentences
# 대응시켜 보면 치환됨을 알 수 있음

['Let it be forgotten as a flower is forgotten,',
 'Forgotten as a fire that once was singing gold.',
 'Let it be forgotten forever and ever.',
 'Time is a kind friend, he will make us old.',
 'If anyone should ask say it was forgotten,',
 'Long and long ago. As a flower, as a fire, as a hushed foot-fall',
 'In a long forgotten snow.']

In [20]:
# 길이 맞춰주기 위해 padding
padded = pad_sequences(sequences, padding='post') 
  # 길이가 짧을 때 어떻게 해줄 거냐(default는 앞쪽 채우기, post는 뒤로)
padded

array([[ 7,  5,  8,  3,  4,  2,  9, 10,  3,  0,  0,  0,  0,  0,  0],
       [ 3,  4,  2, 11, 14, 15, 12, 16, 17,  0,  0,  0,  0,  0,  0],
       [ 7,  5,  8,  3, 18, 13, 19,  0,  0,  0,  0,  0,  0,  0,  0],
       [20, 10,  2, 21, 22, 23, 24, 25, 26, 27,  0,  0,  0,  0,  0],
       [28, 29, 30, 31, 32,  5, 12,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 6, 13,  6, 33,  4,  2,  9,  4,  2, 11,  4,  2, 34, 35, 36],
       [37,  2,  6,  3, 38,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]],
      dtype=int32)

In [22]:
for sequence in sequences:
  sent = []
  for idx in sequence:
    sent.append(tokenizer.index_word[idx])
  print(' '.join(sent)) # sentence 복원하기

let it be forgotten as a flower is forgotten
forgotten as a fire that once was singing gold
let it be forgotten forever and ever
time is a kind friend he will make us old
if anyone should ask say it was forgotten
long and long ago as a flower as a fire as a hushed foot fall
in a long forgotten snow


In [25]:
padded = pad_sequences(sequences, padding='post', maxlen=5)
to_categorical(padded)

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]],

  